function [] = graphPlot(A,xy)
% Author : Shaik Basheeruddin Shah 
% Email ID: bs600@snu.edu.in, Research Scholar, Shiv Nadar University
% Note: If there are any modifications/suggestions, please contact above
% mail ID
% Aim: Plots the 2D-graph for the given adjacency matrix(A) and
% coordinates(xyz). When xyz is omitted, the coordinates generated by using
% 'rand' keywords are used by default

% Checking input arguments and set defaults.
narginchk(1,2);
if nargin<2
    xy = rand(length(A),2);
end
% Generating the node labels and plotting the graph
labels = cellstr(num2str((1:size(xy,1)).'));
figure;
plot(xy(:,1),xy(:,2),'*');
text(xy(:,1),xy(:,2),labels,'HorizontalAlignment','right',...
    'VerticalAlignment','Top');
hold on;
for i = 1:size(A,1)
    for j = i+1:size(A,2)
        if A(i,j)==1
            line([xy(i,1),xy(j,1)],[xy(i,2),xy(j,2)]);
        end
    end
end
end