function [] = graphPlot3(A,xyz)
% Author : Shaik Basheeruddin Shah 
% Email ID: bs600@snu.edu.in, Research Scholar, Shiv Nadar University
% Note: If there are any modifications/suggestions, please contact above
% mail ID
% Aim: Plots the 3D-graph for the given adjacency matrix(A) and coordinates(xyz).
% When xyz is omitted, the coordinates generated by using 'rand' keywords
% are used by default

% Checking input arguments and set defaults.
narginchk(1,2);
if nargin<2
    xyz = rand(length(A),3);
end
labels = cellstr(num2str((1:size(xyz,1)).'));
figure,
plot3(xyz(:,1),xyz(:,2),xyz(:,3),'*');
text(xyz(:,1),xyz(:,2),xyz(:,3),labels,'HorizontalAlignment','right',...
    'VerticalAlignment','Top');
hold on;
for i = 1:size(A,1)
    for j = i+1:size(A,2)
        if A(i,j)==1
            line([xyz(i,1),xyz(j,1)],[xyz(i,2),xyz(j,2)],[xyz(i,3),xyz(j,3)]);
        end
    end
end
end